[workspace]
members = ["relish", "examples/*"]
# Only check / build main crates by default (check all with `--workspace`)
default-members = ["relish"]
resolver = "2"

[workspace.package]
rust-version = "1.80.0"
